Repository viduxka/testingo, pull requests merged in 2020-11, with the labels that each got.

#24 Spring + React + Gradle initialized
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/xebia/springbootreactapp/SpringBootReactAppApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/xebia/springbootreactapp/SpringBootReactAppApplicationTests.java
  build.gradle
  frontend/.gitignore
  frontend/README.md
  frontend/build.gradle
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: infrastructure

#26 #20 remove webjar task and duplication
  frontend/build.gradle
Labels: infrastructure

#25 Closes #20
  backend/build.gradle
  backend/src/main/java/net/vidux/camhub/CamHubApplication.java
  backend/src/test/java/com/xebia/springbootreactapp/SpringBootReactAppApplicationTests.java
  backend/src/test/java/net/vidux/camhub/CamHubApplicationTest.java
Labels: infrastructure

#33 Camera listing endpoint
  backend/build.gradle
  backend/src/main/java/net/vidux/camhub/CamHubApplication.java
  backend/src/main/java/net/vidux/camhub/InMemoryDbInit.java
  backend/src/main/java/net/vidux/camhub/api/CameraRepresentation.java
  backend/src/main/java/net/vidux/camhub/api/CameraRepresentationAssembler.java
  backend/src/main/java/net/vidux/camhub/api/CamerasController.java
  backend/src/main/java/net/vidux/camhub/models/Camera.java
  backend/src/main/java/net/vidux/camhub/repositories/CameraRepo.java
  backend/src/main/java/net/vidux/camhub/repositories/CameraRepoInMemory.java
  backend/src/test/groovy/net/vidux/camhub/repositories/CameraRepoInMemorySpecification.groovy
  backend/src/test/java/net/vidux/camhub/CamHubApplicationTest.java
  backend/src/test/java/net/vidux/camhub/InMemoryDBTest.java
  backend/src/test/java/net/vidux/camhub/TestingWebApplicationTest.java
Labels: backend

#32 Camera list page #27
  backend/src/main/java/net/vidux/camhub/api/CamerasController.java
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/CamListItem/CamListItem.js
  frontend/src/components/CamListItem/CamListItem.module.css
  frontend/src/components/Capability/Capability.js
  frontend/src/components/CapabilityTable/CapabilityTable.js
  frontend/src/components/Discover/Discover.js
  frontend/src/components/Label/Label.js
  frontend/src/components/Label/Label.module.css
  frontend/src/components/Layout/Layout.js
  frontend/src/components/Layout/Layout.module.css
  frontend/src/components/ReserveRelease/ReserveRelease.js
  frontend/src/containers/CamListContainer/CamListContainer.js
  frontend/src/containers/CamListContainer/CamListContainer.module.css
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/reportWebVitals.js
Labels: frontend
